image:
  file: .gitpod.Dockerfile

vscode:
  extensions: 
    - "ms-azuretools.vscode-docker",
    - "ms-kubernetes-tools.vscode-kubernetes-tools",
    - "streetsidesoftware.code-spell-checker",
    - "formulahendry.code-runner",
    - "Gruntfuggly.todo-tree",
    - "DavidAnson.vscode-markdownlint",
    - "inercia.vscode-k3d"
            