version: '3'
services:
  jenkins-master:
    container_name: jenkins
    build:
      context: ./master
      dockerfile: ./Dockerfile
    image: seanly/jenkins:2.414.3-jdk11-base
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc.d/
      JAVA_OPTS: >-
        -server
        -Xmx2g -Xms1g
        -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.LoadStatistics.clock=2000
        -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Shanghai
        -Duser.timezone=Asia/Shanghai
        -Dcom.sun.jndi.ldap.connect.pool.timeout=300000
        -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true
    volumes:
      - jenkins-data:/var/jenkins_home:rw
      - ./master/casc.d:/var/jenkins_home/casc.d/:ro
  jenkins-slave:
    build:
      context: ./slave
      dockerfile: ./Dockerfile
    image: seanly/jenkins:slave-jdk11-dind-rocky8
    restart: unless-stopped
    privileged: true
    depends_on:
      - jenkins-master
    links:
      - jenkins-master
    environment:
      JENKINS_URL: http://jenkins-master:8080
      JENKINS_USR: admin
      JENKINS_PSW: jenkins
      LABELS: docker
      SLAVE_SERVICE: swarm
      CLEANUP_PERIODIC: daily

volumes:
    jenkins-data: