---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    local-pvname: pv-jenkins-master-0
  name: pv-jenkins-master-0
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-volume
  local:
    path: /data/opsbox/data/jenkins/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.opsbox.dev/building
          operator: In
          values:
          - "jenkins-master"
