apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-master
  name: jenkins-master
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: slave
    port: 50000
    protocol: TCP
    targetPort: slave
  selector:
    app: jenkins-master
  type: ClusterIP